#workflow:
#  rules:
#    #- if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#    #  when: always
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'first-phase' && $CI_PIPELINE_SOURCE == 'merge_request_event'
#      when: always
#      # if: $CI_COMMIT_BRANCH == 'cicd-test'
#      # when: always
#
#
#.curl_template: &curl_template |
#  curl -X PUT --header "PRIVATE-TOKEN: $API_TOKEN" "https://vs.ekenya.co.ke:1126/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/merge"

image: docker:20.10.21
stages:
#  - test
  - build
#  - merge

#runTests:
#    stage: test
#    image: node
#    script:
#    - npm run test

buildLatestContainer:
  stage: build
  image: docker:20.10.21
#  rules:
  #- if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'first-phase'
  #  when: always
  #- if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'cicd-test'
  #  when: never
  script:
    - docker login -u test-dev-account -p $REGISTRY_PASSWORD devops-registry.ekenya.co.ke
    - docker build . -t devops-registry.ekenya.co.ke/channel-manager/portal:latest
    - docker push devops-registry.ekenya.co.ke/channel-manager/portal:latest


#mergeChanges:
#  stage: merge
#  script:
#    - wget https://github.com/moparisthebest/static-curl/releases/download/v7.87.0/curl-amd64
#    - mv curl-amd64 /usr/local/bin/curl
#    - chmod +x /usr/local/bin/curl
#    - *curl_template
