workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'first-phase'
      when: always
    - if: $CI_COMMIT_BRANCH == 'cicd-testing' || $CI_COMMIT_BRANCH == 'first-phase'
      when: always

image: docker:20.10.21

stages:
  - preBuild
  - test
  - build

buildBaseContainer:
  stage: preBuild
  script:
    - docker login -u test-dev-account -p $REGISTRY_PASSWORD devops-registry.ekenya.co.ke
    - docker build . -t devops-registry.ekenya.co.ke/channel-manager/portal-builder:latest -f builder.Dockerfile
    - docker push devops-registry.ekenya.co.ke/channel-manager/portal-builder:latest
  only:
    changes:
      - package.json

#runTests:
#    stage: test
#    image: devops-registry.ekenya.co.ke/channel-manager/portal-builder:latest
#    script:
#    - ng test

buildLatestContainer:
  stage: build
  script:
    - docker login -u test-dev-account -p $REGISTRY_PASSWORD devops-registry.ekenya.co.ke
    - docker build . -t devops-registry.ekenya.co.ke/channel-manager/portal:latest
    - docker push devops-registry.ekenya.co.ke/channel-manager/portal:latest
