workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'developer' || $CI_COMMIT_BRANCH == 'cicd-testing' || $CI_COMMIT_BRANCH == 'developer' || $CI_COMMIT_BRANCH == 'uat'
      when: always

.curl_template: &trigger_awx_deploy_to_testing |
 curl --insecure --header "X-Gitlab-Token: $AWX_WEBHOOK_KEY" -X POST $AWX_WEBHOOK_URL -H "Content-Type: application/json" -d '{"ci_commit_sha" : "'"$CI_COMMIT_SHA"'", "deploy_environment" : "'"$DEPLOY_ENVIRONMENT"'", "tag" : "false", "deploy_branch" : "'"$DEPLOY_BRANCH"'" }'

.notify_teams: &notify_teams |
 curl --insecure -X POST -H "Content-Type: application/json" -d '{ "title": "TRA Deployment Successful ", "appName": "Customer Portal", "description": "'"$GITLAB_USER_NAME"' committed: '"$CI_COMMIT_TITLE"'" , "notificationUrl": "https://test-portal.ekenya.co.ke/tra-customer-portal", "targetGroupChatId":"19:5289d22e5e894a499db1f713ce1a980d@thread.v2"}' $TEAMS_NOTIFICATION_API

stages:
  - preBuild
  - build
  - deploy
  - notify

buildBaseImage:
  stage: preBuild
  tags:
    - angular
  image:
    name: node:16.16.0
  script:
    - npm install -g @angular/cli@14.2.9
    - yarn install
    - ng build --configuration production --base-href /tra-customer-portal/ --deploy-url /tra-customer-portal/
  artifacts:
    paths:
      - dist/
      - package*.json
    expire_in: 1 week
    when: always

buildImage:
  stage: build
  needs:
    - job: buildBaseImage
      artifacts: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'development' || $CI_COMMIT_BRANCH == 'development')
      variables:          
        IMAGE_TAG: "latest"
    - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'uat' || $CI_COMMIT_BRANCH == 'uat')
      variables:
        IMAGE_TAG: "uat"
  script:
    - /kaniko/executor
      --context "$PWD"
      --dockerfile "Dockerfile"
      --destination devops-registry.ekenya.co.ke/tra-project/customer-portal:"$IMAGE_TAG"

deploy-application:
  stage: deploy
  image: devops-registry.ekenya.co.ke/library/busybox-with-curl:latest
  variables:
    DEPLOY_ENVIRONMENT: "development"
    DEPLOY_BRANCH: "developer"
  rules:
    - if: $CI_COMMIT_BRANCH == 'cicd-testing' || $CI_COMMIT_BRANCH == 'developer'
      variables:                            
        DEPLOY_BRANCH: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - if: $CI_COMMIT_BRANCH == 'uat'
      when: never        
  script:
    - *trigger_awx_deploy_to_testing

notify-teams:
  stage: notify
  image: curlimages/curl:latest
  needs:
    - job: deploy-application
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'uat'
      when: never     
  script:
    - sleep 600
    - *notify_teams
