version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: ams_frontend
    ports:
      - "5035:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: ams_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db.json:/app/db.json
    restart: always
